## Starting

In [5]:
import pandas as pd 
import duckdb 
import json

In [6]:
data_file = "data/candidates.csv"

con = duckdb.connect("/Users/estevaolins/Development/challenge_Fullstack/data/candidates.db")
con.execute(
    "CREATE TABLE data_candidates AS SELECT * FROM read_csv(?)",
    [data_file],
)

print(con.execute(f"select * from data_candidates limit 10;").fetchall())

[('Bernadette', 'Langworth', 'leonard91@yahoo.com', datetime.date(2021, 2, 26), 'Norway', 2, 'Intern', 'Data Engineer', 3, 3), ('Camryn', 'Reynolds', 'zelda56@hotmail.com', datetime.date(2021, 9, 9), 'Panama', 10, 'Intern', 'Data Engineer', 2, 10), ('Larue', 'Spinka', 'okey_schultz41@gmail.com', datetime.date(2020, 4, 14), 'Belarus', 4, 'Mid-Level', 'Client Success', 10, 9), ('Arch', 'Spinka', 'elvera_kulas@yahoo.com', datetime.date(2020, 10, 1), 'Eritrea', 25, 'Trainee', 'QA Manual', 7, 1), ('Larue', 'Altenwerth', 'minnie.gislason@gmail.com', datetime.date(2020, 5, 20), 'Myanmar', 13, 'Mid-Level', 'Social Media Community Management', 9, 7), ('Alec', 'Abbott', 'juanita_hansen@gmail.com', datetime.date(2019, 8, 17), 'Zimbabwe', 8, 'Junior', 'Adobe Experience Manager', 2, 9), ('Allison', 'Jacobs', 'alba_rolfson27@yahoo.com', datetime.date(2018, 5, 18), 'Wallis and Futuna', 19, 'Trainee', 'Sales', 2, 9), ('Nya', 'Skiles', 'madisen.zulauf@gmail.com', datetime.date(2021, 12, 9), 'Myanmar', 1, 'Lead', 'Mulesoft', 2, 5), ('Mose', 'Lakin', 'dale_murazik@hotmail.com', datetime.date(2018, 3, 13), 'Italy', 18, 'Lead', 'Social Media Community Management', 7, 10), ('Terrance', 'Zieme', 'dustin31@hotmail.com', datetime.date(2022, 4, 8), 'Timor-Leste', 25, 'Lead', 'DevOps', 2, 0)]

In [17]:
df = pd.read_sql_query("SELECT * FROM data_candidates", con)

/var/folders/qf/b7c4tph96rsd0s5h29pl2yp80000gn/T/ipykernel_66118/2738621692.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query("SELECT * FROM data_candidates", con)

In [18]:
data_candidates = pd.DataFrame(df)

In [19]:
data_candidates.head(10)

,First Name,Last Name,Email,Application Date,Country,YOE,Seniority,Technology,Code Challenge Score,Technical Interview Score
0,Bernadette,Langworth,leonard91@yahoo.com,2021-02-26,Norway,2,Intern,Data Engineer,3,3
1,Camryn,Reynolds,zelda56@hotmail.com,2021-09-09,Panama,10,Intern,Data Engineer,2,10
2,Larue,Spinka,okey_schultz41@gmail.com,2020-04-14,Belarus,4,Mid-Level,Client Success,10,9
3,Arch,Spinka,elvera_kulas@yahoo.com,2020-10-01,Eritrea,25,Trainee,QA Manual,7,1
4,Larue,Altenwerth,minnie.gislason@gmail.com,2020-05-20,Myanmar,13,Mid-Level,Social Media Community Management,9,7
5,Alec,Abbott,juanita_hansen@gmail.com,2019-08-17,Zimbabwe,8,Junior,Adobe Experience Manager,2,9
6,Allison,Jacobs,alba_rolfson27@yahoo.com,2018-05-18,Wallis and Futuna,19,Trainee,Sales,2,9
7,Nya,Skiles,madisen.zulauf@gmail.com,2021-12-09,Myanmar,1,Lead,Mulesoft,2,5
8,Mose,Lakin,dale_murazik@hotmail.com,2018-03-13,Italy,18,Lead,Social Media Community Management,7,10
9,Terrance,Zieme,dustin31@hotmail.com,2022-04-08,Timor-Leste,25,Lead,DevOps,2,0

In [20]:
data_candidates.describe()

                YOE  Code Challenge Score  Technical Interview Score
count  50000.000000          50000.000000               50000.000000
mean      15.286980              4.996400                   5.003880
std        8.830652              3.166896                   3.165082
min        0.000000              0.000000                   0.000000
25%        8.000000              2.000000                   2.000000
50%       15.000000              5.000000                   5.000000
75%       23.000000              8.000000                   8.000000
max       30.000000             10.000000                  10.000000

## Intermediate

In [22]:
data_candidates.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 10 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   First Name                 50000 non-null  str
 1   Last Name                  50000 non-null  str
 2   Email                      50000 non-null  str
 3   Application Date           50000 non-null  object
 4   Country                    50000 non-null  str
 5   YOE                        50000 non-null  int64
 6   Seniority                  50000 non-null  str
 7   Technology                 50000 non-null  str
 8   Code Challenge Score       50000 non-null  int64
 9   Technical Interview Score  50000 non-null  int64
dtypes: int64(3), object(1), str(6)
memory usage: 3.8+ MB

In [23]:
data_candidates.head(10)

,First Name,Last Name,Email,Application Date,Country,YOE,Seniority,Technology,Code Challenge Score,Technical Interview Score
0,Bernadette,Langworth,leonard91@yahoo.com,2021-02-26,Norway,2,Intern,Data Engineer,3,3
1,Camryn,Reynolds,zelda56@hotmail.com,2021-09-09,Panama,10,Intern,Data Engineer,2,10
2,Larue,Spinka,okey_schultz41@gmail.com,2020-04-14,Belarus,4,Mid-Level,Client Success,10,9
3,Arch,Spinka,elvera_kulas@yahoo.com,2020-10-01,Eritrea,25,Trainee,QA Manual,7,1
4,Larue,Altenwerth,minnie.gislason@gmail.com,2020-05-20,Myanmar,13,Mid-Level,Social Media Community Management,9,7
5,Alec,Abbott,juanita_hansen@gmail.com,2019-08-17,Zimbabwe,8,Junior,Adobe Experience Manager,2,9
6,Allison,Jacobs,alba_rolfson27@yahoo.com,2018-05-18,Wallis and Futuna,19,Trainee,Sales,2,9
7,Nya,Skiles,madisen.zulauf@gmail.com,2021-12-09,Myanmar,1,Lead,Mulesoft,2,5
8,Mose,Lakin,dale_murazik@hotmail.com,2018-03-13,Italy,18,Lead,Social Media Community Management,7,10
9,Terrance,Zieme,dustin31@hotmail.com,2022-04-08,Timor-Leste,25,Lead,DevOps,2,0

In [37]:
data_candidates["Full Name"] = data_candidates["First Name"] + " " + data_candidates["Last Name"]
data_candidates.head()

,First Name,Last Name,Email,Application Date,Country,YOE,Seniority,Technology,Code Challenge Score,Technical Interview Score,Full Name
0,Bernadette,Langworth,leonard91@yahoo.com,2021-02-26,Norway,2,Intern,Data Engineer,3,3,Bernadette Langworth
1,Camryn,Reynolds,zelda56@hotmail.com,2021-09-09,Panama,10,Intern,Data Engineer,2,10,Camryn Reynolds
2,Larue,Spinka,okey_schultz41@gmail.com,2020-04-14,Belarus,4,Mid-Level,Client Success,10,9,Larue Spinka
3,Arch,Spinka,elvera_kulas@yahoo.com,2020-10-01,Eritrea,25,Trainee,QA Manual,7,1,Arch Spinka
4,Larue,Altenwerth,minnie.gislason@gmail.com,2020-05-20,Myanmar,13,Mid-Level,Social Media Community Management,9,7,Larue Altenwerth

In [31]:
hires_by_tech = data_candidates.groupby("Technology")[["First Name", "Last Name"]].count()

In [32]:
hires_by_tech

                                         First Name  Last Name
Technology
Adobe Experience Manager                       1954       1954
Business Analytics / Project Management        1878       1878
Business Intelligence                          1934       1934
Client Success                                 1927       1927
Data Engineer                                  1951       1951
Database Administration                        1933       1933
Design                                         1906       1906
DevOps                                         3808       3808
Development - Backend                          1965       1965
Development - CMS Backend                      1882       1882
Development - CMS Frontend                     1934       1934
Development - Frontend                         1887       1887
Development - FullStack                        1961       1961
Game Development                               3818       3818
Mulesoft                                       1973       1973
QA Automation                                  1892       1892
QA Manual                                      1902       1902
Sales                                          1890       1890
Salesforce                                     1874       1874
Security                                       1936       1936
Security Compliance                            1852       1852
Social Media Community Management              2028       2028
System Administration                          2014       2014
Technical Writing                              1901       1901

In [43]:
data_candidates.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   First Name                 50000 non-null  str
 1   Last Name                  50000 non-null  str
 2   Email                      50000 non-null  str
 3   Application Date           50000 non-null  str
 4   Country                    50000 non-null  str
 5   YOE                        50000 non-null  int64
 6   Seniority                  50000 non-null  str
 7   Technology                 50000 non-null  str
 8   Code Challenge Score       50000 non-null  int64
 9   Technical Interview Score  50000 non-null  int64
 10  Full Name                  50000 non-null  str
dtypes: int64(3), str(8)
memory usage: 4.2 MB

In [44]:
from datetime import datetime
data_candidates['Application Date'] = pd.to_datetime(data_candidates['Application Date']).dt.strftime('%Y-%m-%d')
data_candidates.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   First Name                 50000 non-null  str
 1   Last Name                  50000 non-null  str
 2   Email                      50000 non-null  str
 3   Application Date           50000 non-null  str
 4   Country                    50000 non-null  str
 5   YOE                        50000 non-null  int64
 6   Seniority                  50000 non-null  str
 7   Technology                 50000 non-null  str
 8   Code Challenge Score       50000 non-null  int64
 9   Technical Interview Score  50000 non-null  int64
 10  Full Name                  50000 non-null  str
dtypes: int64(3), str(8)
memory usage: 4.2 MB